# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
# This should periodically check for updates in the dependency graph

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci(dependabot):"
